# Site settings
name: 个人博客
email: 467598480@qq.com
author: 一叶竹
url: http://www.wybqq.com
resume_site: http://www.wybqq.com
github: https://github.com/wybqq/
baseurl: "/blog"
description: 学而不思则罔;思而不学则殆;生命不止;折腾不休
meta_description: 一叶竹;个人博客;学而不思则罔;思而不学则殆
motto:  学而不思则罔
banner: 思而不学则殆

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: wybqq

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

